# Generated by Django 3.1.2 on 2020-10-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('current_position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CovidActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('date_started', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('NEGATIVE', 'NEGATIVE'), ('HAS_SYMPTOMS', 'HAS_SYMPTOMS')], max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
    ]
